# -*- coding: utf-8 -*-
"""1er entregable - VISUALIZACIÓN DE LA INFORMACIÓN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1urcOx9s_0EOlcO3f2KDDUq7eik_dk6Ng

# Ranking de Precios de Pasajes Aéreos por Aerolínea y Clase
## Trabajo Práctico 01 — Visualización de Datos Estática

**Dataset:** [Airline Ticket Prices Dataset — Kaggle](https://www.kaggle.com/datasets/syedaeman2212/airline-ticket-prices-dataset)  
**Modelo aplicado:** Modelo de Ben Fry (etapas 1 a 6)  
**Herramienta:** Python · Matplotlib · Pandas

---

## El modelo de visualización de Ben Fry

Este trabajo está inspirado en el modelo de visualización de información propuesto por **Ben Fry**, pionero en visualización de datos y co-creador de Processing.

Fry plantea que visualizar datos no es solo "hacer gráficos", sino un **proceso iterativo y completo** compuesto por siete etapas:

| Nº | Etapa | Propósito |
|---|---|---|
| 1️| **Acquire** | Obtener los datos desde una fuente |
| 2️| **Parse** | Estructurar los datos de forma manipulable |
| 3️| **Filter** | Eliminar ruido o datos irrelevantes |
| 4️| **Mine** | Detectar patrones, relaciones o información útil |
| 5️| **Represent** | Elegir una forma visual para mostrar los datos |
| 6️| **Refine** | Mejorar estética y claridad del gráfico |
| 7️| **Interact** | Hacer que el usuario explore los datos libremente |

Cada etapa está señalizada en esta notebook para que puedas seguir el proceso completo de transformación de datos en información visual útil.

---

##  Análisis de precios de pasajes aéreos

###  ¿De qué trata el dataset?

El dataset contiene información sobre pasajes aéreos con los siguientes atributos:

- **aerolinea**: aerolínea operadora
- **origen / destino**: ciudad de origen y destino
- **distancia_km**: distancia del vuelo en kilómetros
- **clase**: clase del asiento (Economy, Premium Economy, Business, First)
- **dias_antes_salida**: días de anticipación entre la compra y el vuelo
- **precio_USD**: precio del pasaje en dólares estadounidenses

---

### Pregunta de interés

> **¿Cómo cambia el ranking de precio de cada aerolínea según la clase del pasaje? ¿Hay aerolíneas que sean consistentemente caras o baratas, o el orden relativo varía entre clases? ¿Cómo influye la distancia promedio del vuelo en ese precio?**

## Importación de librerías y configuración inicial

En las próximas celdas instalamos e importamos las librerías necesarias para cargar, procesar y visualizar los datos.
"""

!pip install kagglehub pandas matplotlib numpy -q

import warnings
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
import seaborn as sns
from google.colab import files

warnings.filterwarnings('ignore')

"""---
## 1️ Acquire – Adquisición de datos

**Objetivo:** Obtener los datos desde una fuente relevante.

En este proyecto: Usamos el dataset **Airline Ticket Prices** disponible en Kaggle, descargado con la librería `kagglehub`.

Características del dataset:
- Contiene información sobre precios de pasajes aéreos
- Incluye variables de aerolínea, ruta, clase, distancia, anticipación de compra y precio
- La variable objetivo es `precio_USD`

Este paso sienta las bases para todo el análisis posterior.

### Descarga del dataset desde Kaggle
"""

import kagglehub
# Descarga automática del dataset desde Kaggle y guarda en path la ruta de la carpeta donde quedó
path = kagglehub.dataset_download('syedaeman2212/airline-ticket-prices-dataset')
print(f'Dataset descargado en: {path}')

# Listamos los archivos disponibles en el dataset descargado
archivos = os.listdir(path)
for f in archivos:
    print(f)

# Cargamos el primer archivo CSV disponible
csv_path = os.path.join(path, archivos[0])
df_raw = pd.read_csv(csv_path)

# Normalizamos nombres de columnas (eliminamos espacios extra)
df_raw.columns = [c.strip() for c in df_raw.columns]

#Muestra cantidad de filas y columnas.
print(f'Dataset cargado: {df_raw.shape[0]:,} filas × {df_raw.shape[1]} columnas')
print(f'Columnas: {df_raw.columns.tolist()}')
df_raw.head()

"""---
## 2️ Parse – Estructuración

**Objetivo:** Organizar los datos en una estructura manipulable.

Inspeccionamos tipos de datos, valores nulos y estandarizamos los nombres de columnas para que sean consistentes en el resto de la notebook.

- Verificamos que `precio_USD` y `distancia_km` sean numéricos
- Verificamos los valores únicos de `clase` para definir el orden lógico
- Revisamos las aerolíneas presentes en el dataset
"""

#Muestra el tipo de dato en cada columna
print('=== Tipos de datos ===')
print(df_raw.dtypes)
print()
print('=== Valores nulos por columna ===')
print(df_raw.isnull().sum())
print()
print('=== Estadísticas descriptivas ===')
display(df_raw.describe(include='all').T)

# Revisamos los valores únicos de las variables categóricas clave
for col in ['aerolinea', 'clase', 'origen', 'destino']:
    match = [c for c in df_raw.columns if c.lower().replace(' ', '_') == col]
    if match:
        print(f'\n--- {match[0]} ---')
        print(df_raw[match[0]].value_counts(dropna=False))

# Estandarizamos los nombres de columnas para el resto de la notebook
col_rename = {
    'aerolinea':          'Airline',
    'origen':             'Origin',
    'destino':            'Destination',
    'distancia_km':       'Distance_km',
    'clase':              'Class',
    'dias_antes_salida':  'Days_Before_Departure',
    'precio_usd':         'Price_USD'
}
actual_rename = {
    c: col_rename[c.lower().replace(' ', '_')]
    for c in df_raw.columns
    if c.lower().replace(' ', '_') in col_rename
}
df_raw = df_raw.rename(columns=actual_rename)

print('Columnas estandarizadas:')
print(df_raw.columns.tolist())
df_raw.head()

"""---
## 3️ Filter – Filtrado

**Objetivo:** Eliminar ruido y datos irrelevantes.

Aplicamos tres técnicas de **data wrangling**:

**Técnica 1 — Eliminación de nulos:** removemos filas con valores faltantes en las columnas que usaremos en el análisis.

**Técnica 2 — Filtrado de outliers con IQR:** removemos precios atípicos extremos (> 3 × IQR) que distorsionarían los medianos por clase.

**Técnica 3 — Ordenamiento ordinal de `Class`:** definimos el orden lógico de las clases (Economy → First) para que el bump chart se lea de izquierda a derecha en orden creciente de categoría.
"""

df = df_raw.copy()

# Aseguramos tipos numéricos en columnas clave
df['Distance_km']= pd.to_numeric(df['Distance_km'],errors='coerce')
df['Price_USD']    = pd.to_numeric(df['Price_USD'],    errors='coerce')
df['Days_Before_Departure'] = pd.to_numeric(df['Days_Before_Departure'], errors='coerce')


# --- Técnica 1: Eliminación de filas con valores nulos en variables clave ---
required = [c for c in ['Price_USD', 'Airline', 'Class', 'Distance_km', 'Days_Before_Departure'] if c in df.columns]
antes = len(df)
df.dropna(subset=required, inplace=True)
print(f'Filas eliminadas por valores nulos: {antes - len(df):,}')
print(f'Dataset tras dropna: {df.shape[0]:,} filas')

# --- Técnica 2: Filtrado de outliers con IQR ---
Q1 = df['Price_USD'].quantile(0.25)
Q3 = df['Price_USD'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 3 * IQR   #  límite inferior
upper = Q3 + 3 * IQR   #  límite superior

antes = len(df)
df = df[(df['Price_USD'] >= lower) & (df['Price_USD'] <= upper)]

print(f'Filas eliminadas por outliers: {antes - len(df):,} ({100*(antes-len(df))/antes:.1f}%)')
print(f'Rango de precios válidos: ${lower:,.0f} – ${upper:,.0f}')
print(f'Dataset limpio final: {df.shape[0]:,} filas')

# --- Técnica 3: Ordenamiento ordinal de Class ---
# Definimos el orden lógico de las clases para el eje X del bump chart
class_order_candidates = ['Economy', 'Premium Economy', 'Business', 'First']

# Mantenemos solo las clases que existen en el dataset
class_values = df['Class'].dropna().unique().tolist()
class_order  = [c for c in class_order_candidates if c in class_values]

# Si el dataset usa otros nombres, usamos los existentes ordenados
if not class_order:
    class_order = sorted(class_values)

# Convertimos a Categorical con orden definido
df['Class'] = pd.Categorical(df['Class'], categories=class_order, ordered=True)

print('Orden de clases definido:')
print(class_order)

"""---
## 4️ Mine – Análisis y exploración

**Objetivo:** Extraer valor y detectar patrones en los datos.

Calculamos tres agregaciones clave que alimentarán directamente la visualización:

- Precio mediano por aerolínea
- Tabla pivote precio mediano: aerolínea × clase
- Distancia promedio: aerolínea × clase (para el tamaño de los puntos)
- Tabla de ranking derivada de los precios medianos

Usamos la **mediana** para precio (robusta ante outliers) y la **media** para distancia (más representativa de la ruta típica).
"""

# Distancia promedio por aerolínea y clase
pivot_dist = df.pivot_table(
    values='Distance_km', index='Airline',
    columns='Class', aggfunc='mean'
)[class_order]
print('Distancia promedio por aerolínea y clase (km):')
display(pivot_dist.style.background_gradient(cmap='Blues').format('{:,.0f} km'))



# Precio mediano por aerolínea
airline_median = df.groupby('Airline')['Price_USD'].median().sort_values(ascending=False)
print('Precio mediano por aerolínea (USD):')
print(airline_median.to_string())

# Tabla pivote: precio mediano aerolínea × clase
pivot_price = df.pivot_table(
    values='Price_USD', index='Airline',
    columns='Class', aggfunc='median'
)[class_order]   #  ordenamos columnas por clase lógica

print(' Precio mediano por aerolínea y clase (USD):')
display(pivot_price.style.background_gradient(cmap='YlOrRd').format('${:,.0f}'))

"""---
## 5️ Represent – Selección de la representación visual

**Objetivo:** Elegir la forma visual más adecuada para cada hallazgo.

Para responder la pregunta de interés elegimos un **Bump Chart** con tamaño de punto variable.

### ¿Qué es un Bump Chart?

Un Bump Chart muestra cómo cambia el **ranking** de distintas entidades a lo largo de una variable ordenada. Cada línea representa una aerolínea y el eje Y muestra su posición relativa de precio en cada clase.

### ¿Por qué es la forma adecuada para este dataset?

| Variable | Cómo se representa |
|---|---|
| **Aerolínea** | Una línea de color por aerolínea |
| **Clase** | Eje X ordenado (Economy → First) |
| **Ranking de precio** | Posición en el eje Y (1 = más cara, arriba) |
| **Precio mediano** | Anotación numérica debajo de cada punto |
| **Distancia promedio** | Tamaño del punto en cada intersección |

Con un solo gráfico se responde: ¿quién es más caro?, ¿cambia ese orden entre clases?, y ¿vuelan rutas más largas las aerolíneas más caras?
"""

# Definimos acá porque las necesitamos tanto en la viz básica (etapa 5) como en la refinada (etapa 6)
unique_airlines = sorted(df['Airline'].dropna().unique().tolist())   # lista de aerolíneas únicas
x_pos           = {c: i for i, c in enumerate(class_order)}         # posición X de cada clase
n_airlines      = len(unique_airlines)                               # cantidad de aerolíneas
n_clases        = len(class_order)                                   # cantidad de clases

# ─── CREACIÓN DE DF_PLOT ──────────────────────────────────────────────────────
# Necesitamos df_plot y x_pos para poder graficar. Los creamos acá.

# 1. Convertir la tabla pivote de precios a formato largo
df_price = pivot_price.stack().reset_index()
df_price.columns = ['Airline', 'Class', 'Price']

# 2. Calcular la distancia promedio por aerolínea y clase
df_distance = df.groupby(['Airline', 'Class'])['Distance_km'].mean().reset_index()
df_distance.columns = ['Airline', 'Class', 'Distance']

# 3. Combinar precios y distancias
df_plot = pd.merge(df_price, df_distance, on=['Airline', 'Class'], how='left')

# 4. Calcular el ranking dentro de cada clase (1 = más cara)
df_plot['Rank'] = df_plot.groupby('Class')['Price'].rank(ascending=False, method='min').astype(int)

# ─── VISUALIZACIÓN BÁSICA ──────────────────────────────────
# Esta versión muestra la idea del bump chart en su forma más simple,
# sin ningún ajuste estético. Es el punto de partida antes del Refine.

fig_basic, ax_basic = plt.subplots(figsize=(10, 6))  # creamos figura y eje básicos, sin color de fondo

for airline in unique_airlines:                          # iteramos sobre cada aerolínea
    sub = df_plot[df_plot['Airline'] == airline]         # filtramos las filas de esa aerolínea
    xs  = [x_pos[c] for c in class_order if c in sub.set_index('Class').index]   # posición X de cada clase
    ys  = [sub.set_index('Class').loc[c, 'Rank'] for c in class_order            # ranking Y de cada clase
           if c in sub.set_index('Class').index]
    ax_basic.plot(xs, ys, marker='o', label=airline)    # línea recta con puntos, sin suavizado

ax_basic.set_xticks(range(len(class_order)))             # marcas en el eje X
ax_basic.set_xticklabels(class_order)                    # etiquetas con los nombres de clase
ax_basic.set_yticks(range(1, n_airlines + 1))            # marcas en el eje Y
ax_basic.invert_yaxis()                                  # invertimos Y para que rank 1 quede arriba
ax_basic.set_title('Ranking de precio por aerolínea según clase')   # título simple
ax_basic.set_xlabel('Clase')                             # etiqueta eje X
ax_basic.set_ylabel('Ranking (1 = más cara)')            # etiqueta eje Y
ax_basic.legend(loc='upper right')                       # leyenda estándar
ax_basic.grid(True, linestyle='--', alpha=0.5)           # grilla simple

plt.tight_layout()
plt.show()

"""---
## 6️ Refine – Refinamiento visual

**Objetivo:** Mejorar estética, legibilidad e impacto visual.

Decisiones de diseño aplicadas:

- **Color fijo por aerolínea:** asignado dinámicamente con paleta `husl` para máxima distinción
- **Curvas suavizadas** entre puntos usando smoothstep bezier
- **Tamaño del punto proporcional a la distancia promedio** del vuelo
- **Precio mediano anotado** debajo de cada punto (valor real, no solo ranking)
- **Etiquetas directas** al inicio y final de cada línea — sin leyenda separada
- **Fondo oscuro** para maximizar el contraste de los colores
- **Eje Y invertido:** rank 1 arriba = más caro, lectura intuitiva
"""

# ─── PALETA DE COLORES ────────────────────────────────────────────────────────
BG    = '#0D0F1A'   # fondo general
CARD  = '#141624'   # fondo del gráfico
TEXTW = '#F0F4F8'   # texto principal
TEXTG = '#8892A4'   # texto secundario
# Colores dinámicos por aerolínea — paleta husl para máxima distinción
palette        = sns.color_palette('husl', n_colors=len(unique_airlines)).as_hex()
airline_colors = {a: palette[i] for i, a in enumerate(unique_airlines)}

print(' Paleta de colores y variables globales de visualización definidas.')
for airline, color in airline_colors.items():
    print(f'  {airline}: {color}')

# ─── FUNCIÓN DE CURVA SUAVIZADA ───────────────────────────────────────────────
def smooth_line(x0, y0, x1, y1, n=200):
    """Interpolación suavizada entre dos puntos usando función smoothstep"""
    t = np.linspace(0, 1, n)
    s = 3*t**2 - 2*t**3          # smoothstep: arranque y frenado suaves
    return x0 + (x1 - x0) * t, y0 + (y1 - y0) * s

#Asegurar el orden categórico de la columna 'Class'
df_plot['Class'] = pd.Categorical(df_plot['Class'], categories=class_order, ordered=True)
df_plot = df_plot.sort_values(by=['Class', 'Rank'])

# ─── FUNCIÓN DE ESCALA DE TAMAÑO DE PUNTO ─────────────────────────────────────
dist_min = df_plot['Distance'].min()
dist_max = df_plot['Distance'].max()

def dist_to_size(d):
    """Mapea distancia en km a tamaño de punto entre 80 y 500"""
    return 80 + (d - dist_min) / (dist_max - dist_min) * 420

print('Funciones auxiliares y df_plot definidos.')

"""### Construcción de la visualización final"""

# ─── FIGURA PRINCIPAL ─────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 9), facecolor=BG)
ax.set_facecolor(CARD)
for sp in ax.spines.values():
    sp.set_visible(False)   # eliminamos bordes del eje

# ─── GRILLA DE FONDO ──────────────────────────────────────────────────────────
for rank in range(1, n_airlines + 1):
    ax.axhline(rank, color='#1E2235', linewidth=0.8, zorder=1)
for xi in range(n_clases):
    ax.axvline(xi, color='#1E2235', linewidth=1.2, zorder=1)

# ─── BUMP CHART: UNA LÍNEA POR AEROLÍNEA ─────────────────────────────────────
for airline in unique_airlines:
    color = airline_colors[airline]
    sub   = df_plot[df_plot['Airline'] == airline].set_index('Class')

    xs = [x_pos[c] for c in class_order if c in sub.index]
    ys = [sub.loc[c, 'Rank']     for c in class_order if c in sub.index]
    ps = [sub.loc[c, 'Price']    for c in class_order if c in sub.index]
    ds = [sub.loc[c, 'Distance'] for c in class_order if c in sub.index]

    if len(xs) < 2:
        continue

    # Segmentos suavizados entre puntos consecutivos
    for i in range(len(xs) - 1):
        xc, yc = smooth_line(xs[i], ys[i], xs[i+1], ys[i+1])
        ax.plot(xc, yc, color=color, linewidth=3.5, alpha=0.9,
                solid_capstyle='round', zorder=3)

    # Puntos con tamaño proporcional a distancia promedio
    sizes = [dist_to_size(d) for d in ds]
    ax.scatter(xs, ys, color=color, s=sizes, zorder=5,
               edgecolors=BG, linewidths=2)

    # Precio mediano anotado debajo de cada punto
    for xi, yi, price in zip(xs, ys, ps):
        ax.text(xi, yi - 0.28, f'${price:,.0f}',
                ha='center', va='top', fontsize=7.5,
                color=color, fontfamily='monospace', alpha=0.85,
                path_effects=[pe.withStroke(linewidth=2, foreground=CARD)])

    # Etiqueta al inicio (izquierda)
    ax.text(-0.35, ys[0], f'#{ys[0]}  {airline}',
            ha='right', va='center', fontsize=10,
            color=color, fontfamily='monospace', fontweight='bold',
            path_effects=[pe.withStroke(linewidth=3, foreground=BG)])

    # Etiqueta al final (derecha)
    ax.text(n_clases - 0.65, ys[-1], f'{airline}  #{ys[-1]}',
            ha='left', va='center', fontsize=10,
            color=color, fontfamily='monospace', fontweight='bold',
            path_effects=[pe.withStroke(linewidth=3, foreground=BG)])

# ─── LEYENDA DE TAMAÑO DE PUNTO ───────────────────────────────────────────────
for dist_val, label in [
    (dist_min, f'{dist_min:,.0f} km'),
    ((dist_min + dist_max) / 2, f'{(dist_min+dist_max)/2:,.0f} km'),
    (dist_max, f'{dist_max:,.0f} km')
]:
    ax.scatter([], [], s=dist_to_size(dist_val), color=TEXTG,
               alpha=0.6, label=label, edgecolors=BG, linewidths=1.5)
ax.legend(
    title='Distancia promedio',
    title_fontsize=8, fontsize=8,
    framealpha=0, labelcolor=TEXTG,
    loc='lower right',
    prop={'family': 'monospace'}
)

# ─── ANOTACIÓN DEL MOVIMIENTO MÁS LLAMATIVO ───────────────────────────────────
# Detectamos la aerolínea con mayor cambio de ranking entre Economy y la última clase
rank_ini = df_plot[df_plot['Class'] == class_order[0]][['Airline','Rank']].set_index('Airline')['Rank']
rank_fin = df_plot[df_plot['Class'] == class_order[-1]][['Airline','Rank']].set_index('Airline')['Rank']
rank_change   = (rank_fin - rank_ini).abs()
most_changed  = rank_change.idxmax()
rank_end_val  = rank_fin[most_changed]

ax.annotate(
    f'{most_changed}\ncambia más\nentre clases',
    xy=(n_clases - 1, rank_end_val),
    xytext=(n_clases - 1.8, rank_end_val - 1.2),
    color=airline_colors.get(most_changed, TEXTW),
    fontsize=8, fontfamily='monospace',
    arrowprops=dict(
        arrowstyle='->', lw=1.5,
        color=airline_colors.get(most_changed, TEXTW)
    ),
    path_effects=[pe.withStroke(linewidth=2, foreground=CARD)]
)

# ─── EJES Y ETIQUETAS ─────────────────────────────────────────────────────────
ax.set_xlim(-1.9, n_clases + 0.9)
ax.set_ylim(n_airlines + 0.6, 0.3)    # eje Y invertido: rank 1 arriba

ax.set_xticks(range(n_clases))
ax.set_xticklabels(class_order, color=TEXTW, fontsize=11,
                   fontfamily='monospace', fontweight='bold')
ax.tick_params(axis='x', length=0, pad=10)

ax.set_yticks(range(1, n_airlines + 1))
ax.set_yticklabels(
    [f'#{r}' for r in range(1, n_airlines + 1)],
    color=TEXTG, fontsize=9, fontfamily='monospace'
)
ax.tick_params(axis='y', length=0)

# ─── TÍTULO Y SUBTÍTULO ───────────────────────────────────────────────────────
fig.text(
    0.5, 0.97,
    '✈  RANKING DE PRECIO POR AEROLÍNEA SEGÚN CLASE',
    ha='center', va='top', fontsize=14, fontweight='bold',
    color=TEXTW, fontfamily='monospace'
)
fig.text(
    0.5, 0.935,
    f'#1 = más cara · #{n_airlines} = más barata  •  Precio mediano en USD  •  Tamaño del punto = distancia promedio (km)  •  n = {len(df):,}',
    ha='center', va='top', fontsize=9,
    color=TEXTG, fontfamily='monospace'
)

plt.tight_layout(rect=[0, 0, 1, 0.92])
plt.savefig('airline_viz.png', dpi=180, bbox_inches='tight', facecolor=BG)
plt.show()
print(' Visualización guardada como airline_viz.png')

"""---
## Conclusiones

**Pregunta de interés:** *¿Cómo cambia el ranking de precio de cada aerolínea según la clase del pasaje? ¿Hay aerolíneas consistentemente caras, o el orden varía entre clases? ¿Cómo influye la distancia?*

El bump chart permite leer simultáneamente cuatro variables — aerolínea, clase, precio relativo y distancia — en una sola imagen:

### 1. El ranking de precios no es estático entre clases
Las líneas que se cruzan a lo largo del eje X revelan que el orden relativo de precios entre aerolíneas cambia según la clase. Una aerolínea barata en Economy no necesariamente lo es en Business o First.

###2. La relación entre distancia y precio no es consistente
Si bien algunas aerolíneas con puntos grandes (mayor distancia promedio) aparecen en rankings altos, esto no se cumple en todos los casos. Etihad, por ejemplo, tiene puntos de tamaño medio-grande pero se mantiene en los últimos rankings (#7) en las tres clases. La distancia influye pero no es el único factor determinante del precio.

###3. Los mayores cambios de ranking ocurren entre Economy y Business
La mayoría de los cruces de líneas se concentran en el tramo Economy → Business. Entre Business y First los rankings se estabilizan — las líneas se vuelven más paralelas y hay menos cruces. Esto sugiere que la estrategia de precios de las aerolíneas varía más al pasar de cabina económica a premium que dentro de las cabinas premium.


### Síntesis final

> El bump chart revela que el ranking de precios entre aerolíneas no es estático — cambia significativamente según la clase del pasaje. Esto indica que elegir aerolínea sin considerar la clase puede llevar a decisiones subóptimas: la aerolínea más cara en Economy no necesariamente lo es en Business o First, y viceversa. La distancia promedio del vuelo influye en el precio pero no es el único factor determinante.
"""
